export const LAUNCH = 'LAUNCH';

export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const SELECT_PHRASE = 'SELECT_PHRASE';

export const OPEN_EXPANDED_VIEW = 'OPEN_EXPANDED_VIEW';
export const CLOSE_EXPANDED_VIEW = 'CLOSE_EXPANDED_VIEW';